# Docker Compose file for Malwarecage end-to-end test suite

version: "3.3"
services:
  mwdb:
    build:
      context: .
      dockerfile: deploy/docker/Dockerfile
    depends_on:
      - postgres
      - redis
    image: certpl/malwarecage
    restart: on-failure
    env_file:
      # NOTE: use gen_vars.sh in order to generate this file
      - mwdb-vars.env
  malwarefront:
    depends_on:
      - mwdb
    build:
      context: .
      dockerfile: deploy/docker/Dockerfile-web
    image: certpl/malwarecage-web
    ports:
      - "80:80"
    restart: on-failure
  postgres:
    image: postgres
    restart: always
    env_file:
      # NOTE: use gen_vars.sh in order to generate this file
      - postgres-vars.env
  mwdb-tests:
    build: tests/backend
    image: certpl/malwarecage-tests
    env_file:
      - mwdb-vars.env
  redis:
    image: redis:alpine
