# Docker Compose file for mwdb-core development environment

version: "3.3"
services:
  mwdb:
    build:
      context: ../..
      dockerfile: ./deploy/docker/Dockerfile
    ports:
      - "127.0.0.1:8080:8080"
    depends_on:
      - postgres
      - redis
    environment:
      MWDB_POSTGRES_URI: "postgresql://mwdb:dev-postgres-password@postgres./mwdb"
    image: certpl/mwdb
    restart: on-failure
    volumes:
      - "../../docker/mail_templates:/app/mail_templates"
      - "../mwdb.ini:/etc/mwdb-core/mwdb.ini"
      - mwdb-uploads:/app/uploads
  mwdb-web:
    depends_on:
      - mwdb
    image: certpl/mwdb-web
    build:
      context: ../..
      dockerfile: ./deploy/docker/Dockerfile-web
    ports:
      - "127.0.0.1:80:3000"
    environment:
      HOST: 0.0.0.0
      REACT_APP_API_URL: "/api/"
      NODE_ENV: production
    restart: on-failure
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: mwdb
      POSTGRES_DB: mwdb
      POSTGRES_PASSWORD: dev-postgres-password
    ports:
      - "127.0.0.1:54322:5432"
    volumes:
      - mwdb-postgres:/var/lib/postgresql/data
  redis:
    image: redis:alpine
  mailhog:
    image: mailhog/mailhog:latest
    ports:
      - "127.0.0.1:8025:8025"
volumes:
  mwdb-postgres:
  mwdb-uploads:
