version: "3.3"
services:
  minio:
    image: minio/minio
    command: "server --address 0.0.0.0:9000 --console-address :8070 /data"
    volumes:
      - /tmp/minio:/data
    ports:
      - "127.0.0.1:9000:9000"
      - "127.0.0.1:8070:8070"
    environment:
      - MINIO_ROOT_USER=mwdb-test-access
      - MINIO_ROOT_PASSWORD=mwdb-test-key
