name: "Build and test Malwarecage"
on:
  push:
    branches:
    - master
    - ci/*
  pull_request:
    branches:
    - master
jobs:
  build_core:
    name: Build Malwarecage core image
    runs-on: ubuntu-latest
    env:
      DOCKER_BUILDKIT: 1
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Build and push Malwarecage image
        uses: docker/build-push-action@v1.1.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          dockerfile: ./deploy/docker/Dockerfile
          repository: certpl/malwarecage
          tag_with_sha: true
  build_frontend:
    name: Build Malwarecage frontend image
    runs-on: ubuntu-latest
    env:
      DOCKER_BUILDKIT: 1
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Build and push Malwarefront image
        uses: docker/build-push-action@v1.1.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          dockerfile: ./deploy/docker/Dockerfile-web
          repository: certpl/malwarecage-web
          tag_with_sha: true
  build_e2e:
    name: Build e2e test image
    runs-on: ubuntu-latest
    env:
      DOCKER_BUILDKIT: 1
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Build test image
        uses: docker/build-push-action@v1.1.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          dockerfile: ./tests/Dockerfile
          repository: certpl/malwarecage-tests
          path: tests
          tag_with_sha: true
  
          
  