name: "Build and test Malwarecage"
on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master
jobs:
  build_core:
    name: Build Malwarecage core image
    runs-on: ubuntu-latest
    env:
      DOCKER_BUILDKIT: 1
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Build and push Malwarecage image
        uses: docker/build-push-action@v1.1.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          dockerfile: ./deploy/docker/Dockerfile
          repository: certpl/malwarecage
          tags: ${{ github.sha }}
          push: ${{ github.event == 'push' }}
      - name: Store Malwarecage image 
        run: docker save -o ./malwarecage-image certpl/malwarecage:${{ github.sha }}
      - name: Upload Malwarecage image
        uses: actions/upload-artifact@v2 
        with:
          name: malwarecage-image
          path: malwarecage-image
  build_frontend:
    name: Build Malwarecage frontend image
    runs-on: ubuntu-latest
    env:
      DOCKER_BUILDKIT: 1
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Build and push Malwarefront image
        uses: docker/build-push-action@v1.1.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          dockerfile: ./deploy/docker/Dockerfile-web
          repository: certpl/malwarecage-web
          tags: ${{ github.sha }}
          push: ${{ github.event == 'push' }} 
      - name: Store Malwarefront image 
        run: docker save -o ./malwarecage-web-image certpl/malwarecage-web:${{ github.sha }}
      - name: Upload Malwarefront image
        uses: actions/upload-artifact@v2 
        with:
          name: malwarecage-web-image
          path: malwarecage-web-image
  build_e2e:
    name: Build e2e test image
    runs-on: ubuntu-latest
    env:
      DOCKER_BUILDKIT: 1
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Build and push test image
        uses: docker/build-push-action@v1.1.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          dockerfile: ./tests/backend/Dockerfile
          repository: certpl/malwarecage-tests
          path: tests/backend
          tags: ${{ github.sha }}
          push: ${{ github.event == 'push' }} 
      - name: Store test image 
        run: docker save -o ./malwarecage-tests-image certpl/malwarecage-tests:${{ github.sha }}
      - name: Upload test image
        uses: actions/upload-artifact@v2 
        with:
          name: malwarecage-tests-image
          path: malwarecage-tests-image
  test_e2e:
    needs: [build_core, build_frontend, build_e2e] 
    name: Perform e2e tests
    runs-on: ubuntu-latest
    env:
      DOCKER_BUILDKIT: 1
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Download all artifacts
        uses: actions/download-artifact@v2
      - name: Import images
        run: |
          docker load --input ./malwarecage-image/malwarecage-image
          docker load --input ./malwarecage-web-image/malwarecage-web-image
          docker load --input ./malwarecage-tests-image/malwarecage-tests-image
          docker tag certpl/malwarecage:$GITHUB_SHA certpl/malwarecage:latest
          docker tag certpl/malwarecage-web:$GITHUB_SHA certpl/malwarecage-web:latest
          docker tag certpl/malwarecage-tests:$GITHUB_SHA certpl/malwarecage-tests:latest
      - name: Setup configuration      
        run: |
          chmod +x gen_vars.sh
          ./gen_vars.sh test
      - name: Perform tests
        run: |
          docker-compose -f docker-compose-e2e.yml up -d
          docker-compose -f docker-compose-e2e.yml logs -f -t mwdb-tests
          docker wait malwarecage_mwdb-tests_1
