name: "Build and test Malwarecage"
on:
  push:
    branches:
    - master
    - ci/*
  pull_request:
    branches:
    - master
jobs:
  build_mwdb:
    name: Build Malwarecage
    runs-on: ubuntu-latest
    env:
      - DOCKER_BUILDKIT: 1
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Build and push Malwarecage image
        uses: docker/build-push-action@v1.1.0
        with:
          tag_with_sha: true
          push: false
          dockerfile: ./deploy/docker/Dockerfile
        