name: "Build and test mwdb-core"
on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master
jobs:
  lint_core:
    name: Lint mwdb-core core sources
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: 3.6
      - run: pip install -r dev-requirements.txt
      - run: isort --check mwdb/
      - run: black --check mwdb/
      - run: flake8 mwdb/
  lint_web:
    name: Lint mwdb-core web sources
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Install dev dependencies
        working-directory: mwdb/web
        run: npm install --only dev
      - name: Check if code was prettified
        working-directory: mwdb/web
        run: npx prettier --check src
  build_core:
    needs: [lint_core]
    name: Build mwdb-core core image
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        if: ${{ github.event_name == 'push' }}
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push mwdb-core image
        uses: docker/build-push-action@v2
        with:
          file: ./deploy/docker/Dockerfile
          tags: |
            certpl/mwdb:${{ github.sha }}
            certpl/mwdb:master
          push: ${{ github.event_name == 'push' }}
      - name: Store mwdb-core image
        run: docker save -o ./mwdb-image certpl/mwdb:${{ github.sha }}
      - name: Upload mwdb-core image
        uses: actions/upload-artifact@v2 
        with:
          name: mwdb-image
          path: mwdb-image
  build_frontend:
    needs: [lint_web]
    name: Build mwdb-core web image
    runs-on: ubuntu-latest
    env:
      DOCKER_BUILDKIT: 1
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        if: ${{ github.event_name == 'push' }}
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push mwdb-core image
        uses: docker/build-push-action@v2
        with:
          file: ./deploy/docker/Dockerfile-web
          tags: |
            certpl/mwdb-web:${{ github.sha }}
            certpl/mwdb-web:master
          push: ${{ github.event_name == 'push' }}
      - name: Store mwdb-core web image
        run: docker save -o ./mwdb-web-image certpl/mwdb-web:${{ github.sha }}
      - name: Upload mwdb-core web image
        uses: actions/upload-artifact@v2 
        with:
          name: mwdb-web-image
          path: mwdb-web-image
  build_backend_e2e:
    name: Build backend e2e test image
    runs-on: ubuntu-latest
    env:
      DOCKER_BUILDKIT: 1
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build and push mwdb-core image
        uses: docker/build-push-action@v2
        with:
          file: ./tests/backend/Dockerfile
          tags: |
            certpl/mwdb-tests:${{ github.sha }}
          push: false
      - name: Store test image
        run: docker save -o ./mwdb-tests-image certpl/mwdb-tests:${{ github.sha }}
      - name: Upload test image
        uses: actions/upload-artifact@v2 
        with:
          name: mwdb-tests-image
          path: mwdb-tests-image
  build_frontend_e2e:
    name: Build frontend e2e test image
    runs-on: ubuntu-latest
    env:
      DOCKER_BUILDKIT: 1
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build and push mwdb-core image
        uses: docker/build-push-action@v2
        with:
          file: ./tests/frontend/Dockerfile
          tags: |
            certpl/mwdb-web-tests:${{ github.sha }}
          push: false
      - name: Store test image
        run: docker save -o ./mwdb-web-tests-image certpl/mwdb-web-tests:${{ github.sha }}
      - name: Upload test image
        uses: actions/upload-artifact@v2
        with:
          name: mwdb-web-tests-image
          path: mwdb-web-tests-image
  test_backend_e2e:
    needs: [build_core, build_frontend, build_backend_e2e]
    name: Perform backend e2e tests
    runs-on: ubuntu-latest
    env:
      DOCKER_BUILDKIT: 1
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Download all artifacts
        uses: actions/download-artifact@v2
      - name: Import images
        run: |
          docker load --input ./mwdb-image/mwdb-image
          docker load --input ./mwdb-web-image/mwdb-web-image
          docker load --input ./mwdb-tests-image/mwdb-tests-image
          docker tag certpl/mwdb:$GITHUB_SHA certpl/mwdb:latest
          docker tag certpl/mwdb-web:$GITHUB_SHA certpl/mwdb-web:latest
          docker tag certpl/mwdb-tests:$GITHUB_SHA certpl/mwdb-tests:latest
      - name: Setup configuration      
        run: |
          chmod +x gen_vars.sh
          ./gen_vars.sh test
      - name: Perform tests
        run: |
          docker-compose -f docker-compose-e2e.yml up -d mwdb-tests
          docker-compose -f docker-compose-e2e.yml logs -f -t mwdb-tests
          ([ $(docker wait mwdb-core_mwdb-tests_1) == 0 ])
      - name: Job failed - storing application logs
        if: ${{ failure() }}
        run: |
          docker-compose -f docker-compose-e2e.yml logs --no-color -t mwdb > ./mwdb-e2e-logs
      - name: Job failed - upload application logs
        if: ${{ failure() }}
        uses: actions/upload-artifact@v2
        with:
          name: mwdb-e2e-logs
          path: mwdb-e2e-logs
  test_frontend_e2e:
    needs: [build_core, build_frontend, build_frontend_e2e]
    name: Perform frontend e2e tests
    runs-on: ubuntu-latest
    env:
      DOCKER_BUILDKIT: 1
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Download all artifacts
        uses: actions/download-artifact@v2
      - name: Import images
        run: |
          docker load --input ./mwdb-image/mwdb-image
          docker load --input ./mwdb-web-image/mwdb-web-image
          docker load --input ./mwdb-web-tests-image/mwdb-web-tests-image
          docker tag certpl/mwdb:$GITHUB_SHA certpl/mwdb:latest
          docker tag certpl/mwdb-web:$GITHUB_SHA certpl/mwdb-web:latest
          docker tag certpl/mwdb-web-tests:$GITHUB_SHA certpl/mwdb-web-tests:latest
      - name: Setup configuration
        run: |
          chmod +x gen_vars.sh
          ./gen_vars.sh test
      - name: Perform tests
        run: |
          docker-compose -f docker-compose-e2e.yml up -d web-tests
          docker-compose -f docker-compose-e2e.yml logs -f -t web-tests
          ([ $(docker wait mwdb-core_web-tests_1) == 0 ])
